# Generated by Django 6.0.2 on 2026-02-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('podcast', 'Podcast'), ('libro', 'Libro')], max_length=20)),
                ('proveedor', models.CharField(choices=[('youtube', 'YouTube'), ('spotify', 'Spotify'), ('cloudflare', 'Cloudflare Stream'), ('otro', 'Otro')], max_length=30)),
                ('url_externa', models.URLField()),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
