# Generated by Django 5.2.1 on 2026-03-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0002_alter_contenido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='categoria',
            field=models.CharField(blank=True, choices=[('novedades', 'Novedades'), ('eventos', 'Eventos'), ('podcast', 'Podcast')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contenido',
            name='seccion',
            field=models.CharField(blank=True, choices=[('cac_contigo', 'La CAC Contigo'), ('un_dia_con', 'Un día con')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
